FightmasterTeamsBundle:
    resource: "@FightmasterTeamsBundle/Resources/config/routing.xml"
    prefix:   /

FightmasterTournamentsDashboardBundle:
    resource: "@FightmasterTournamentsDashboardBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
